/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AIUM2 (https://sketchfab.com/alfredonicolas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rabbit-4cf175ddd8d94c7f8705d0d3b9586e6e
Title: Rabbit
*/

import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { a } from '@react-spring/three';
import bunnyModel from '../assets/3d/bunny.glb';

const Bunny = (props) => {
    const bunnyRef = useRef();
    const { nodes, materials } = useGLTF(bunnyModel);

    useFrame(() => {
        bunnyRef.current.rotation.y += 0.01; // Ajuste a velocidade da rotação conforme necessário
    });

    return (
        <a.group ref={bunnyRef} {...props} dispose={null}>
            <mesh
                geometry={nodes.Object_5.geometry}
                material={materials.material_0}
                scale={0.01}
            />
        </a.group>
    );
};

useGLTF.preload(bunnyModel);

export default Bunny;
