/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Blaž Mraz (https://sketchfab.com/Mraz3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/acoustic-guitar-402aa42f0faa4845878cf005e66a1046
Title: Acoustic Guitar
*/

import React, { useRef } from 'react';
// import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { a } from '@react-spring/three';
import guitarModel from '../assets/3d/guitar.glb';

const Guitar = (props) => {
    const guitarRef = useRef();

    const { nodes, materials } = useGLTF(guitarModel)

    return (
        <a.group ref={guitarRef} {...props} dispose={null}>
            <group scale={0.01}>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <group position={[0, 0.052, 0.598]} rotation={[-0.182, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sideboards_Glossy_Black_0.geometry}
                            material={materials.Glossy_Black}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sideboards_Wood_Sides_0.geometry}
                            material={materials.Wood_Sides}
                        />
                    </group>
                    <group position={[0, 0.052, 0.598]} rotation={[-0.182, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Backboard_Wood_Back_0.geometry}
                            material={materials.Wood_Back}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Backboard_Glossy_Black_0.geometry}
                            material={materials.Glossy_Black}
                        />
                    </group>
                    <group position={[-0.027, -0.048, 0.322]} rotation={[-0.182, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bridge_pins_Markings_0.geometry}
                            material={materials.Markings}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bridge_pins_Glossy_Black_0.geometry}
                            material={materials.Glossy_Black}
                        />
                    </group>
                    <group position={[0.006, 0.059, 0.594]} rotation={[2.959, -Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Kerfing_interior_Kerfing_interior_0.geometry}
                            material={materials.Kerfing_interior}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Kerfing_interior_Kerfing_interior_0_1.geometry}
                            material={materials.Kerfing_interior}
                        />
                    </group>
                    <group position={[0.01, 0.058, 0.602]} rotation={[-0.728, 1.266, -0.783]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Button_Brass_polished_0.geometry}
                            material={materials.Brass_polished}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Button_Glossy_Black_0.geometry}
                            material={materials.Glossy_Black}
                        />
                    </group>
                    <group position={[-0.001, -0.035, 0.126]} rotation={[-0.182, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Button001_Brass_polished_0.geometry}
                            material={materials.Brass_polished}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Button001_Glossy_Black_0.geometry}
                            material={materials.Glossy_Black}
                        />
                    </group>
                    <group position={[-0.001, 0.118, 0.534]} rotation={[0, 0, Math.PI / 2]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bar_Brass_polished_0.geometry}
                            material={materials.Brass_polished}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Bar_Glossy_Black_0.geometry}
                            material={materials.Glossy_Black}
                        />
                    </group>
                    <group position={[0.001, -0.036, 0.365]} rotation={[-0.182, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Rossete_Glossy_Black_0.geometry}
                            material={materials.Glossy_Black}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Rossete_Lining_0.geometry}
                            material={materials.Lining}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Binding_front_and_back_Lining_0.geometry}
                        material={materials.Lining}
                        position={[0, 0.052, 0.598]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Binding_top_Lining_0.geometry}
                        material={materials.Lining}
                        position={[0, 0.052, 0.598]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Front_board_Sounboard_0.geometry}
                        material={materials.Sounboard}
                        position={[0.001, -0.036, 0.365]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Pickguard_Pickguard_0.geometry}
                        material={materials.Pickguard}
                        position={[0.077, -0.026, 0.427]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Bridge_Bridge_0.geometry}
                        material={materials.Bridge}
                        position={[-0.001, -0.019, 0.461]}
                        rotation={[1.388, 0, -Math.PI / 2]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['Saddle_Saddle&Nut_0'].geometry}
                        material={materials.SaddleNut}
                        position={[-0.001, -0.019, 0.461]}
                        rotation={[1.388, 0, -Math.PI / 2]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Bracing_Interior_0.geometry}
                        material={materials.Interior}
                        position={[0.003, 0.069, 0.49]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Neck_Glossy_Black_0.geometry}
                        material={materials.Glossy_Black}
                        position={[-0.001, 0.065, 0.861]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Neck_Cap_Lining_0.geometry}
                        material={materials.Lining}
                        position={[-0.001, 0.065, 0.861]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Fretboard_Fretboard_0.geometry}
                        material={materials.Fretboard}
                        position={[-0.001, 0.065, 0.861]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['Fretboar_Nut_Saddle&Nut_0'].geometry}
                        material={materials.SaddleNut}
                        position={[-0.001, 0.065, 0.861]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Fretboard_Binding_Lining_0.geometry}
                        material={materials.Lining}
                        position={[-0.001, 0.065, 0.861]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Fretboard_Frets_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[-0.001, 0.054, 0.889]}
                        rotation={[-0.182, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Markers_Markings_0.geometry}
                        material={materials.Markings}
                        position={[-0.001, 0.057, 0.89]}
                        rotation={[1.388, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Tunner_Houseing_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[0.019, 0.101, 0.958]}
                        rotation={[-0.418, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Tunner_Houseing_Screws_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[0.013, 0.095, 0.95]}
                        rotation={[-0.418, -1.217, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Tunner_Axel_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[0.042, 0.102, 0.961]}
                        rotation={[1.153, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Tunner_Knob_Screws_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[0.048, 0.102, 0.961]}
                        rotation={[-1.028, 0, -Math.PI / 2]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Tunner_Peg_Washers_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[0.02, 0.112, 1.031]}
                        rotation={[1.153, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.ButtonScrew_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[0.013, 0.058, 0.603]}
                        rotation={[0.083, -0.213, -1.352]}
                        scale={0.904}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.ButtonScrew001_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[-0.001, -0.036, 0.122]}
                        rotation={[-1.753, 0, 0]}
                        scale={0.904}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Strings_Strings_0.geometry}
                        material={materials.Strings}
                        position={[0.018, 0.055, 0.972]}
                        rotation={[1.388, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Tunner_Pegs_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[0.018, 0.081, 0.971]}
                        rotation={[1.153, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Tunner_Knobs_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[0.042, 0.102, 0.961]}
                        rotation={[1.153, 0, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Legs_Stand_0.geometry}
                        material={materials.Stand}
                        position={[-0.001, 0.118, 0.534]}
                        rotation={[0, 0, Math.PI / 2]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Joint_Brass_polished_0.geometry}
                        material={materials.Brass_polished}
                        position={[-0.001, 0.118, 0.534]}
                        rotation={[0, 1.361, Math.PI / 2]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Pading001_Pading_0.geometry}
                        material={materials.Pading}
                        position={[-0.001, 0.118, 0.533]}
                        rotation={[0, 0, Math.PI / 2]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Pading_Pading_0.geometry}
                        material={materials.Pading}
                        position={[-0.001, 0.118, 0.534]}
                        rotation={[0, 0, Math.PI / 2]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Pading002_Pading_0.geometry}
                        material={materials.Pading}
                        position={[-0.001, 0.118, 0.534]}
                        rotation={[0, 0, Math.PI / 2]}
                    />
                </group>
            </group>
        </a.group>
    )
}

useGLTF.preload(guitarModel);

export default Guitar;